imports:
    - { resource: "@SWPAnalyticsBundle/Resources/config/app/config.yml" }

parameters:
    swp.resources: []

services:
    _defaults:
        autowire: true
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    swp.analytics.analytics_event_listener:
        class:  SWP\Bundle\AnalyticsBundle\EventListener\AnalyticsEventListener
        arguments:
            - '@old_sound_rabbit_mq.analytics_event_producer'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 249 }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 1 }
            - { name: kernel.event_listener, event: kernel.finish_request, method: onKernelFinishRequest, priority: 1 }
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate, priority: 1 }